language: node_js

node_js:
  - 10
  - 9
  - 8
  - 7.6
  - node

script: "npm run coveralls"

after_success:
  - sudo apt-get install git
  - chmod +x .travis/push.sh
  - .travis/push.sh

branches:
  only:
  - master